### ISSUE TITLE
ScalarIncDec

### ISSUE THREAD

**Issue by beached** [codingupastorm/vadersharp#1]
This might be my lack of understanding but shouldn't 
https://github.com/codingupastorm/vadersharp/blob/master/VaderSharp/VaderSharp/SentimentUtils.cs#L205

be 
```
double scalar = BoosterDict[wordLower];
```

**Comment by codingupastorm** [comment]
Hey, thanks for reviewing. You're right - I'll amend as soon as I get a chance.

**Comment by beached** [comment]
Playing around porting it to C++ and it seemed like that would throw on a capitalized word

**Comment by codingupastorm** [comment]
Makes sense. Cheers for pull req
