### ISSUE TITLE
WordsPlusPunc, GetWordsAndEmoticons,... : Might be replaced with Regex

### ISSUE THREAD

**Issue by Chr1st1anSzech** [codingupastorm/vadersharp#6]
I'm still pondering, however, it might be replaced with a regex. You want to check if your list contains this word + punctuation?

**Comment by codingupastorm** [comment]
Hey bud, cheers for the idea but it seems that regex is actually significantly slower for this situation. Can you check out the comments on the pull req? 

Changes to SentimentUtils are good though if you want to submit them separately
