### ISSUE TITLE
Multi Target Framework Support

### ISSUE THREAD

**Issue by NimaAra** [codingupastorm/vadersharp#8]
This is a very nice library. 

Please consider adding support for other frameworks or at the minimum a version of the full framework e.g. `net40` or `net452`. At the moment I cannot use your _NuGet_ anywhere other than where _netstandard1.6_ is supported.

_FYI_, you can take a look at some of my repositories ([THIS](https://github.com/NimaAra/Easy.MessageHub) or [THIS](https://github.com/NimaAra/Easy.Logger)) on how to enable multi target framework support in _NuGet_.

Alternatively let me know and I will be happy to send over a pull request.

**Comment by codingupastorm** [comment]
This is definitely important. I haven't developed for multi platform support on NuGet before, but I'll have a look at your links and try to replicate. 

If you want to send over a pull request that would be very appreciated actually!

**Comment by NimaAra** [comment]
Okay no problem for that I will need to migrate the solution to _Visual Studio 2017_, is that going to be a problem?

**Comment by codingupastorm** [comment]
It's currently VS 2017 :)

**Comment by NimaAra** [comment]
Even better! Okay leave it with me I will take care of it.

**Comment by NimaAra** [comment]
Just submitted #12.

**Comment by codingupastorm** [comment]
Excellent thanks very much @NimaAra. I will review and hopefully accept within the next day or so :)

**Comment by NimaAra** [comment]
Great, you may want to upgrade the [README.md](https://github.com/codingupastorm/vadersharp/blob/master/README.md) to reflect the increased support. The project now supports the following:

Supports .Net Core (.Net 3.5 & netstandard1.3) running on:

* .Net Core
* .Net Framework 3.5 and above
* Mono & Xamarin
* UWP

Feel free to close this issue as I can see you have managed to merge the pull request.
